spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      # ddl-auto: none
  cloud:
    aws:
      region:
        static: ${S3_REGION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        endpoint: ${S3_ENDPOINT}
        path-style-access-enabled: true

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}